version: '2'
services:
  web:
    build: ./Docker/web/
    hostname: paymentgateway-demo
    domainname: dev.big.hu
    environment:
      - DEVELOPMENT_USER=${USER}
      - PMGW_URL_TEST=http://paymentgateway.vkrisztian.dev.big.hu
    volumes:
      - ./:/var/www/dev/paymentgateway-demo
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:paymentgateway-demo.dev.big.hu
    network_mode: bridge
